---
- name: Windows server test
  hosts: all
  gather_facts: no

  tasks:
  - name: Save the result of 'whoami' in 'whoami'
    win_command: whoami
    register: whoami
#    changed_when: whoami_out.stdout_lines
#  - debug: msg="{{ whoami_out.stdout }}"
#  - debug: var=whoami.stdout_lines

    
  # Execute a command in the remote shell
  - name: Save the result of 'netstat -nr' in 'netstat'
    win_shell: netstat -nr
    register: netstat
#    changed_when: netstat_out.stdout_lines
#  - debug: msg="{{ netstat_out.stdout }}"  
#  - debug: var=netstat.stdout_lines
#  - debug:
#    var: netstat.stdout_lines
  - debug:
      var: netstat.stdout_lines
